### ISSUE TITLE
GUI checklist

### ISSUE THREAD

**Issue by Claudius-Appel** [Claudius-Appel/duflor.gui#3]
- [ ] - checkbox: use parallelisation
    - [x] select the number of used cores
    - [ ] dev-input: set-cores\d+
- [ ] 
- [ ] When Analysis has finished, open up a modal
    - [ ] Open Output-Folder?

**Comment by Claudius-Appel** [comment]
Closed as outdated
