### ISSUE TITLE
test rcmd-check on `macos-latest`/`release`

### ISSUE THREAD

**Issue by Claudius-Appel** [Claudius-Appel/duflor.gui#73]
I have no idea if it works, but I should probably consider it.
- [ ] setup on `dev_2`
- [ ] update action-yaml
- [ ] commit to dev2
- [ ] push to GH, see if it passes macos-latest/release
