### ISSUE TITLE
hotfix #79 - update duflor-dependency version and renv-lockfile after bump to r4.4.0

### ISSUE THREAD

**Issue by Claudius-Appel** [Claudius-Appel/duflor.gui#80]
when updating the package to  4.4.0, the duflor-dependency was left at 1.0.0, instead of being reinstalled to 1.0.1.

- [x] re-install duflor 1.0.1 from GH
- [x] update the renv-lock in duflorgui
- [x] update version
- [x] rebuild docs
- [ ] update pkg-cite data
